# Generated by Django 5.2.1 on 2025-05-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bringing',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bringing', to='events.event'),
            preserve_default=False,
        ),
    ]
