# Generated by Django 5.2.1 on 2025-05-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
    ]
